# **Algèbre Linéaire de base avec NumPy**

<figure style="padding: 1em;">
    <img src="img/0.numpy-linear.jpg" width="700" height="500" alt="">
</figure>


>> L'algèbre linéaire est la branche des mathématiques qui se concentre sur les équations linéaires.   

Les concepts de l'**algèbre linéaire sont cruciaux pour comprendre la théorie derrière le Machine Learning (ML), en particulier celle du Deep Learning**. Ils vous donnent une meilleure intuition sur le fonctionnement des algorithmes, ce qui vous permet de prendre de meilleures décisions. Donc, **si vous voulez vraiment être un professionnel** dans ce domaine, vous ne pouvez pas échapper à la maîtrise de certains de ses concepts.    

Ce notebook vous donnera une introduction générale aux concepts les plus importants de l'algèbre linéaire de base utilisés dans le ML.


**NB:** **Vous n'avez pas forcément besoin de maitriser l'algèbre linéaire avant de commencer avec le Machine Learning, mais à un moment donné, vous voudrez peut-être mieux comprendre comment les différents algorithmes fonctionnent vraiment en coulisses**.

#### **I. Objets mathématiques en algèbre linéaire**

En algèbre linéaire, les données sont représentées par des équations linéaires, qui sont présentées sous forme de **matrices et de vecteurs**.   
Par conséquent, vous traitez principalement avec des matrices et des vecteurs plutôt qu'avec des scalaires. Lorsque vous disposez des bonnes bibliothèques, comme **Numpy**, vous pouvez effectuer des multiplications de matrices complexes très facilement avec seulement quelques lignes de code.

<figure style="padding: 1em;">
    <img src="img/math-objects.png" width="500" height="300" alt="">
</figure>

##### **1. Scalaire:**
Un scalaire est simplement un **nombre unique**.   
Par exemple **24**.

In [38]:
import numpy as np

scalaire = 24
print(scalaire)
print(type(scalaire))

24
<class 'int'>


In [39]:
scalaire = np.array(24)
print(scalaire)
print(type(scalaire))

24
<class 'numpy.ndarray'>


##### **2. Vecteur:**
Un vecteur est un **tableau ordonné de nombres et peut être en ligne ou en colonne**. Un vecteur a juste un indice unique, qui peut pointer vers une valeur spécifique dans le vecteur.   

Par exemple, **V[2]** se réfère à la deuxième valeur dans le vecteur, qui est -6 dans le graphique précedent.

<figure style="padding: 1em;">
    <img src="img/2.vector.jpg" width="500" height="300" alt="">
</figure>

In [40]:
vecteur = np.array([2, -6, 9])
print(vecteur)

[ 2 -6  9]


In [41]:
vecteur[1]

np.int64(-6)

In [42]:
vecteur = np.array([[2], 
                    [-6], 
                    [9]
                    ])
print(vecteur)

[[ 2]
 [-6]
 [ 9]]


##### **3. Matrice:**
Une matrice est un **tableau 2D ordonné de nombres et elle a deux indices**. Le premier pointe vers la ligne et le second vers la colonne.  

Par exemple, **M[2,3]** se réfère à la valeur dans la deuxième ligne et la troisième colonne, qui est -7 dans le graphique jaune ci-dessus. Une matrice peut avoir plusieurs lignes et colonnes. 

> **NB:** Un vecteur est aussi une matrice, mais avec une seule ligne ou une seule colonne.

La matrice dans l'exemple du graphique jaune est également une matrice dimensionnelle 2 par 3 (lignes x colonnes). Ci-dessous, vous pouvez voir un autre exemple de matrice ainsi que sa notation :

<figure style="padding: 1em;">
    <img src="img/3.matrix.jpg" width="500" height="300" alt="">
</figure>

In [43]:
matrice = np.array([[1, 2, 3], 
                    [4, 5, 6]
                    ])
print(matrice)

[[1 2 3]
 [4 5 6]]


In [44]:
matrice = np.array([[7,   8,  9, 10], 
                    [11, 12, 13, 14], 
                    [15, 16, 17, 18]
                    ])
print(matrice)

[[ 7  8  9 10]
 [11 12 13 14]
 [15 16 17 18]]


##### **4. Tenseur:**
Vous pouvez penser à un tenseur comme **un tableau de nombres, arrangé sur une grille régulière, avec un nombre variable d'axes**. Un tenseur a trois indices, où le premier pointe vers la ligne, le second vers la colonne et le troisième vers l'axe.   

Par exemple, **T[2,3,2]** pointe vers la deuxième ligne, la troisième colonne et le second axe. Cela se réfère à la valeur 0 dans le tenseur de droite dans le graphique ci-dessous :

<figure style="padding: 1em;">
    <img src="img/4.tensor.png" width="500" height="300" alt="">
</figure>

In [45]:
tenseur = np.array([[[1, 2], [3, 4]], 
                    [[5, 6], [7, 8]]
                    ])
print(tenseur)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [46]:
tenseur = np.array([[[9, 10, 11],  [12, 13, 14]], 
                    [[15, 16, 17], [18, 19, 20]], 
                    [[21, 22, 23], [24, 25, 26]]
                ])
print(tenseur)

[[[ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]]

 [[21 22 23]
  [24 25 26]]]



> **NB:** **Le tenseur est le terme le plus général pour tous ces concepts ci-dessus car un tenseur est un tableau multidimensionnel et il peut être un vecteur et une matrice**, selon le nombre d'indices qu'il a. 
> Par exemple:
> - un tenseur de premier ordre serait un vecteur (1 indice). 
> - un tenseur de second ordre est une matrice (2 indices) et 
> - les tenseurs de troisième ordre (3 indices) et plus sont appelés des tenseurs d'ordre supérieur (3 indices ou plus).

#### **II. Règles de calcul de l'algèbre linéaire**

##### **1. Opérations Matrice-Scalaire**

Si vous multipliez, divisez, soustrayez ou ajoutez un scalaire à une matrice, vous le faites avec chaque élément de la matrice (avec NumPy notamment).
L'image ci-dessous illustre cela parfaitement pour la multiplication :

<figure style="padding: 1em;">
    <img src="img/5..jpg" width="500" height="300"  alt="">
</figure>


##### **2. Multiplication Matrice-Vecteur**
Multiplier une matrice par un vecteur peut être considéré comme multiplier chaque ligne de la matrice par la colonne du vecteur. **Le résultat sera un vecteur qui a le même nombre de lignes que la matrice.**   

L'image ci-dessous montre comment cela fonctionne :

<figure style="padding: 1em;">
    <img src="img/6..jpg" width="400" height="200"  alt="">
</figure>

<figure style="padding: 1em;">
    <img src="img/7..jpg" width="400" height="200"  alt="">
</figure>


Pour mieux comprendre le concept, nous passerons en revue le calcul de la deuxième image. 

- Pour obtenir la première valeur du vecteur résultant (16), nous prenons les nombres du vecteur que nous voulons multiplier avec la matrice (1 et 5), et les multiplions avec les nombres de la première ligne de la matrice (1 et 3). Cela ressemble à ceci : `1*1 + 3*5 = 16`

- Nous faisons de même pour les valeurs de la deuxième ligne de la matrice : `4*1 + 0*5 = 4`

- Et encore pour la troisième ligne de la matrice : `2*1 + 1*5 = 7`

Voici un autre exemple :
<figure style="padding: 1em;">
    <img src="img/8..jpg" width="500" height="300"  alt="">
</figure>

**Et voici une forme plus générale :**
<figure style="padding: 1em;">
    <img src="img/10..jpg" width="500" height="300" alt="">
</figure>


##### **3. Addition et soustraction Matrice-Matrice**

L'addition et la soustraction matrice-matrice sont assez faciles et directes. **La condition est que les matrices aient les mêmes dimensions** et donc le résultat est une matrice qui a également les mêmes dimensions.   

Vous ajoutez ou soustrayez simplement chaque valeur de la première matrice avec sa valeur correspondante dans la deuxième matrice. Voir ci-dessous :

<figure style="padding: 1em;">
    <img src="img/11..jpg" width="500" height="300" alt="">
</figure>


#### **4. Multiplication Matrice-Matrice**

Multiplier deux matrices ensemble n'est pas si difficile non plus si vous savez comment multiplier une matrice par un vecteur.   

Notez que vous ne pouvez multiplier des matrices ensemble que **ssi le nombre de colonnes de la première matrice correspond au nombre de lignes de la deuxième matrice.** Le résultat sera une matrice avec le même nombre de lignes que la première matrice et le même nombre de colonnes que la deuxième matrice. 

Cela fonctionne comme suit :

Vous divisez simplement la deuxième matrice en colonnes-vecteurs et multipliez la première matrice séparément par chacune de ces colonnes. Ensuite, vous mettez les résultats dans une nouvelle matrice (sans les additionner !). L'image ci-dessous explique cela étape par étape :

<figure style="padding: 1em;">
    <img src="img/12..jpg" width="400" height="300"  alt="">
</figure>


**Une forme plus générale!**
<figure style="padding: 1em;">
    <img src="img/13.jpg" width="500" height="300" alt="">
</figure>

#### **III. Propriétés de la Multiplication de Matrices**

La multiplication de matrices a plusieurs propriétés qui nous permettent de regrouper beaucoup de calculs en une seule multiplication de matrices. Nous les discuterons une par une ci-dessous. Nous commencerons par expliquer ces concepts avec des scalaires et ensuite avec des matrices car cela vous donnera une meilleure compréhension du processus.

##### **1. Non Commutatif**

La multiplication scalaire est commutative mais la multiplication de matrices ne l'est pas.  

Cela signifie que lorsque nous multiplions des scalaires, **7\*3 est le même que 3\*7**.   
Mais lorsque nous multiplions des matrices entre elles, **A\*B n'est pas le même que B\*A**.

In [47]:
### exemple de multiplication scalaire (commutatif)
scalaire1 = 7
scalaire2 = 3
print(scalaire1 * scalaire2 == scalaire2 * scalaire1)  # True

True


In [48]:
### exemple de multiplication de matrices (non commutatif)
A = np.array([[1, 2], 
              [3, 4]
              ])

B = np.array([[2, 0], 
              [1, 2]
              ])



In [49]:
np.dot(A, B)

array([[ 4,  4],
       [10,  8]])

In [50]:
np.dot(B, A)

array([[ 2,  4],
       [ 7, 10]])

In [51]:
# Vérifier l'égalité (mais là il y aura un probléme!!!)
print(np.dot(A, B) == np.dot(B, A))

[[False  True]
 [False False]]


In [52]:
print(np.allclose(np.dot(A, B), np.dot(B, A)))  # False

False


##### **2. Associatif**

La multiplication scalaire et la multiplication de matrices sont **toutes deux associatives.** 

Cela signifie que la multiplication scalaire **4\*(5\*3) est la même que (4\*5)\*3** et que la multiplication de matrices **A(B\*C) est la même que (A\*B)C.**

In [53]:
scalaire3 = 5
scalaire4 = 3

print((scalaire1 * (scalaire3 * scalaire4)) == ((scalaire1 * scalaire3) * scalaire4))

True


In [54]:
C = np.array([[0, 1], 
              [2, 3]
              ])

left_associative = np.dot(A, np.dot(B, C))
right_associative = np.dot(np.dot(A, B), C)

print(np.allclose(left_associative, right_associative))

True


##### **3. Distributif**

La multiplication scalaire et la multiplication de matrices sont également **toutes deux distributives**. 

Cela signifie que **3(5 + 3) est le même que 3\*5 + 3\*3 et que A(B+C) est le même que A\*B + A\*C.**


In [55]:
### exemple de multiplication scalaire (distributif)
print(scalaire1 * (scalaire3 + scalaire4) == (scalaire1 * scalaire3 + scalaire1 * scalaire4))

True


In [56]:
### exemple de multiplication de matrices (distributif)
D = np.array([[1, 1], [1, 1]])
left_distributive = np.dot(A, (B + D))
right_distributive = np.dot(A, B) + np.dot(A, D)

print(np.allclose(left_distributive, right_distributive))

True


##### **4. Matrice Identité**

La matrice identité est un type spécial de matrice mais d'abord, nous devons définir ce qu'est une identité. 

Le nombre 1 est une identité car tout ce que vous multipliez par 1 est égal à lui-même. Par conséquent, chaque matrice qui est multipliée par une matrice identité est égale à elle-même. Par exemple, la matrice A multipliée par sa matrice identité est égale à A.

Vous pouvez repérer une matrice identité par le fait qu'**elle a des uns le long de ses diagonales et que chaque autre valeur est zéro.** C'est aussi une **"matrice carrée"**, ce qui signifie que son nombre de lignes correspond à son nombre de colonnes.

<figure style="padding: 1em;">
    <img src="img/14..jpg" width="500" height="300" alt="">
</figure>

In [57]:
### exemple de matrice identité
I = np.eye(2)

print(np.allclose(np.dot(A, I), A))

True


In [58]:
print(np.allclose(np.dot(I, A), A))

True


Nous avons précédemment discuté que la multiplication de matrices n'est pas commutative mais il y a une exception, à savoir si nous multiplions une matrice par une matrice identité. Par conséquent, l'équation suivante est vraie : **A\*I = I\*A = A**

#### **IV. Inverse et Transposé**

L'inverse de la matrice et le transposé de la matrice sont deux types particuliers de propriétés de matrices.  
Encore une fois, nous commencerons par discuter de la manière dont ces propriétés se rapportent aux nombres réels, puis de la manière dont elles se rapportent aux matrices.

##### **1. Inverse**

Tout d'abord, qu'est-ce qu'un inverse ? **Un nombre qui est multiplié par son inverse est égal à 1.** 

Notez que **chaque nombre sauf 0 a un inverse. Si vous multipliez une matrice par son inverse, le résultat est sa matrice identité.** 

L'exemple ci-dessous montre à quoi ressemble l'inverse des scalaires :

<figure style="padding: 1em;">
    <img src="img/15.jpg" width="500" height="200" alt="">
</figure>

**Mais toutes les matrices n'ont pas un inverse.** Vous pouvez calculer l'inverse d'une matrice si c'est une "matrice carrée" et si elle a un inverse. 

> **NB:** Discuter des matrices qui ont un inverse serait malheureusement hors du cadre de ce cours.

Pourquoi avons-nous besoin d'un inverse ? Parce que nous ne pouvons pas diviser des matrices.   
Il n'y a pas de concept de division par une matrice mais nous pouvons multiplier une matrice par un inverse, ce qui revient essentiellement à la même chose.

L'image ci-dessous montre une matrice multipliée par son inverse, ce qui donne une matrice identité 2 par 2.

<figure style="padding: 1em;">
    <img src="img/16.jpg" width="500" height="300" alt="">
</figure>

Vous pouvez facilement calculer l'inverse d'une matrice (si elle en a un) en utilisant Numpy. Voici le lien vers la documentation : [https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.linalg.inv.html](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.linalg.inv.html).

In [59]:
### exemple d'inverse de matrice (simple)
A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [60]:
### autre exemple d'inverse de matrice (complexe)
B = np.array([[4, 7], [2, 6]])
B_inv = np.linalg.inv(B)
print(B_inv)

[[ 0.6 -0.7]
 [-0.2  0.4]]


In [61]:
### vérification : multiplication de A par son inverse donne la matrice identité
I = np.dot(A, A_inv)
print(I)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [62]:
### autre vérification : multiplication de B par son inverse donne la matrice identité
I_complex = np.dot(B, B_inv)
print(I_complex)

[[ 1.00000000e+00 -1.11022302e-16]
 [-1.11022302e-16  1.00000000e+00]]


##### **2. Transposé**

Et enfin, nous discuterons de la propriété de transposé de la matrice. 

Il s'agit essentiellement de **l'image miroir d'une matrice, le long d'un axe de 45 degrés.**  
Il est assez simple d'obtenir le transposé d'une matrice. 

Sa première colonne est la première ligne du transposé de la matrice et la deuxième colonne est la deuxième ligne du transposé de la matrice. Une matrice m*n est transformée en une matrice n*m. 

**De plus, l'élément A[i, j] de A est égal à l'élément A[j, i] (transposé).** L'image ci-dessous illustre cela :

<figure style="padding: 1em;">
    <img src="img/17.jpg" width="500" height="300" alt="">
</figure>

In [63]:
### exemple de transposé de matrice
A_transpose = np.transpose(A)
print(A_transpose)

[[1 3]
 [2 4]]


#### **IV. Prise en main de NumPy et Approfondissement**

**NumPy ("Numerical Python")** est l'une des bibliothèques les plus puissantes de l'écosystème Python, en particulier pour les tâches nécessitant des calculs numériques de haute performance et la manipulation de données. 


##### **1. Tableaux NumPy (déjà vu!)**
Pour créer un tableau dans NumPy, vous pouvez utiliser la fonction `numpy.array()`. Cette fonction prend un objet semblable à une séquence (liste, tuple, un autre tableau, etc.) et le convertit en un tableau.


In [64]:
import numpy as np

### tableau simple à partir d'une liste
simple_array = np.array([1, 2, 3, 4, 5])
print(simple_array)

[1 2 3 4 5]


In [65]:
### tableau 2D à partir d'une liste de listes
two_dim_array = np.array([[1, 2], [3, 4], [5, 6]])
print(two_dim_array)

[[1 2]
 [3 4]
 [5 6]]


##### **2. Caractéristiques des tableaux NumPy : dimensions, forme, taille, type de Données**

Une fois que vous avez créé un tableau NumPy, il est crucial de comprendre ses caractéristiques pour l'utiliser efficacement.  
Ces caractéristiques incluent **les dimensions, la forme, la taille et le type de données :**

- **Dimensions** : c'est simplement son "rang". Un tableau 1D a un rang de 1, un tableau 2D a un rang de 2, etc.
- **Forme** : décrit la taille le long de chacune de ses dimensions. Par exemple, pour un **tableau 2D avec m lignes et n colonnes, la forme serait A=(m,n)**.
- **Taille** : nombre total d'éléments dans le tableau. Pour un **tableau 2D de forme (m,n), la taille serait m×n.**
- **Type de données** : type des éléments contenus dans le tableau, noté `dtype`. Les types de données courants incluent les entiers (`int`), les flottants (`float`) et les nombres complexes (`complex`).

Par exemple, considérons un tableau A de forme (3,2) :

In [66]:
A = np.array([[1, 2], 
              [3, 4], 
              [5, 6]
              ])

### dimensions
print("Dimensions :", A.ndim)

### forme
print("Forme :", A.shape )

### taille
print("Taille :", A.size)

### type de Données
print("Type de Données :", A.dtype)

Dimensions : 2
Forme : (3, 2)
Taille : 6
Type de Données : int64


#### **3. Indexation, Slicing et Reshape des Tableaux NumPy**

- **Accès aux éléments du tableau (Indexation):**
L'indexation est l'opération qui vous permet d'accéder à des éléments individuels au sein d'un tableau. 

Pour accéder à un élément particulier A[i,j] dans un tableau 2D **A**, vous utilisez i pour spécifier la ligne et j pour spécifier la colonne.

In [67]:
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]
              ])

print(A)

### accéder à l'élément de la première ligne et de la deuxième colonne
element = A[2, 1]  

print(f"Element indexé: {element}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element indexé: 8


- **Slicing des tableaux pour créer des sous-tableaux:**
Le slicing est une opération polyvalente qui vous permet de créer des sous-tableaux à partir d'un tableau plus grand. Cela se fait en utilisant la notation `start:stop:step`, où :

  - `start`: indice de départ (inclus).
  - `stop`: indice de fin (exclus).
  - `step`: intervalle entre chaque indice.

In [68]:
### créer un sous-tableau avec les 2 premières lignes et les 2 premières colonnes
sub_array = A[0:2, 0:2]  

print(sub_array)

[[1 2]
 [4 5]]


In [69]:
sub_array = A[0::2, 0::2] 
sub_array

array([[1, 3],
       [7, 9]])

- **Reshape des tableaux pour changer leurs dimensions:**
Le reshape est une fonctionnalité puissante de NumPy qui vous permet de changer les dimensions de votre tableau sans altérer les données sous-jacentes. Le principe fondamental à garder à l'esprit est que le produit des dimensions doit rester constant.

In [70]:
### reshape d'un tableau 3x3 en un tableau 1x9

reshaped_array = A.reshape(1, 9)  
print(reshaped_array)

[[1 2 3 4 5 6 7 8 9]]


Dans cet exemple, 3×3=1×9, satisfaisant l'équation de reshape m×n=p×q.


##### **Approfondissement: 3. Broadcasting des tableaux NumPy**

Le broadcasting dans NumPy fait référence à l'**ensemble des règles qui permettent des opérations binaires élémentaires sur des tableaux d'entrées de formes ou de dimensions différentes**. 


Contrairement aux opérations algébriques linéaires typiques qui nécessitent des dimensions congruentes, le broadcasting vous permet d'étendre implicitement des tableaux plus petits à la forme de tableaux plus grands, permettant ainsi des calculs plus rapides et plus efficaces en termes de mémoire.


- **Pourquoi le broadcasting est utile?**

Le broadcasting simplifie le code et améliore les performances en éliminant le besoin de boucles explicites et de réplication des données.

Cela est particulièrement bénéfique lors du traitement de grands ensembles de données, où la duplication explicite pourrait entraîner des inefficacités de calcul ou des contraintes de mémoire.  

De plus, comme le broadcasting est implémenté au niveau C dans NumPy, il est nettement plus rapide que les opérations au niveau Python.

- **Règles et scénarios où le broadcasting s'applique:**

Pour appliquer le broadcasting, certaines règles doivent être suivies. Plus précisément, les dimensions sont considérées de droite à gauche, et pour chaque dimension :

  - Si les tailles de dimension sont égales, continuez.
  - Si l'une des dimensions est 1, alors étendez-la pour correspondre à l'autre dimension.

**En termes mathématiques, le broadcasting d'un tableau (m,n) avec un tableau (m,1) ou (1,n) donnera un tableau (m,n).** 

**Exprimé comme une équation :** (m,n) tableau avec (m,1) ou (1,n) tableau donne (m,n) tableau

In [71]:
A = np.array([[1, 2], 
              [3, 4], 
              [5, 6]
              ]) 

B = np.array([1, 2])

### broadcasting de B sur A
C = A + B
C

array([[2, 4],
       [4, 6],
       [6, 8]])

In [72]:
A = np.array([[1, 2], 
              [3, 4], 
              [5, 6]
              ]) 

B = np.array([[1],
              [2],
              [3]])

### broadcasting de B sur A
C = A + B
C

array([[2, 3],
       [5, 6],
       [8, 9]])

Ici, le tableau B de forme (1,2) est broadcasté sur A de forme (3,2), ce qui donne un nouveau tableau (3,2) C.


#### **Petit cadeau de fin pour les plus matheux: Calcul de valeurs et de vecteurs propres**

Les problèmes de valeurs propres apparaissent souvent dans diverses applications comme l'analyse de la stabilité des systèmes et les graphiques informatiques. NumPy offre un moyen efficace de résoudre ces problèmes grâce à la fonction `numpy.linalg.eig()`, qui renvoie à la fois les valeurs propres et les vecteurs propres d'une matrice carrée.

In [73]:
import numpy as np

A = np.array([[1, 2], 
              [3, 4]
              ])

### calculer les valeurs propres et les vecteurs propres
eigenvalues, eigenvectors = np.linalg.eig(A)
eigenvalues, eigenvectors

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))